### ISSUE TITLE
TODOS Orga - 20180702

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/itp-diy-syllabus#23]
## TODO:
- [ ] add `count` property and increment the counter for each time the resource is submitted
- [ ] create GET request to pull popular tags via API from our DB and add to browser extension for easier search and tagging (see below)
- [ ] create API endpoint to pull popular tags and add to browser extension for easier search and tagging (see above)
- [ ] rating / commenting 
- [ ] need to find a good way to add titles, decriptions, and images to pages without <meta> tags
- [ ] Authentication/login mechanism
- [ ] add `info` and `view submissions` pages to chrome extension ==> maybe it is a good time to think about a more robust framework that can plug into a web app elsewhere? (e.g. react or next.js)
- [ ] design proposals
- [ ] concepting for `mortar` for  `learning bricks`
- [ ] Create a list of representative webpages as a "representative" sample to test against for: automated keyword extraction, identification of quirks, etc.
- [ ] handle collaborative aspect of working with learning resources and pathways ==> what does student/teacher collaboration look like? how do we keep track of progress? forking and building off of other pathways?
- [ ] "expiration date" feature for resources ==> need to find a good way to continue vetting resources / make sure they are current
- [ ] contributors highlight page ==> thank you page for contributors (https://github.com/joeyklee/itp-diy-syllabus/issues/15) 

## DONE:
- [X] add feature counter
